[package]
name = "docuum"
version = "0.21.1"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2021"
description = "LRU eviction of Docker images."
license = "MIT"
documentation = "https://github.com/stepchowfun/docuum"
homepage = "https://github.com/stepchowfun/docuum"
repository = "https://github.com/stepchowfun/docuum"
readme = "README.md"

[dependencies]
atty = "0.2"
byte-unit = "4"
chrono = "0.4"
colored = "2"
dirs = "3"
env_logger = "0.8"
log = "0.4"
scopeguard = "1"
serde_json = "1.0"
serde_yaml = "0.8"
tempfile = "3"
regex = "1.5.5"

[target.'cfg(target_os = "linux")'.dependencies]
sysinfo = "0.23.5"

[dependencies.clap]
version = "2"
features = ["wrap_help"]

[dependencies.serde]
version = "1"
features = ["derive"]
